appname = "TMPFiles"
description = "Cette appliction sert à partager des fichiers avec d'autre personne par l'intermediaire d'un serveur qui fait office d'emplacement de stockage temporaire"
[web]
address = "0.0.0.0"
port = 3000
# domain = ""
# path = "/"
[store]
path = "tmp/store"